name: Continuous Integration

# This workflow will run on every commit to check code quality and vulnerabilities.
on: {}

jobs:
    # this will build the artifacts needed for deploy using the npm run build command
    Inspect:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install --dev

            - name: Run Linter
              run: npm run lint

            - name: Run Formatter
              run: npm run format
