name: Release

# This workflow will run on main branch to build, test and deploy frontend application.
# SCM release tag will be created on repository as well.
on:
    push:
        branches:
            - main
            - develop

jobs:
    # this will build the artifacts needed for deploy using the npm run build command
    build:
        runs-on: ubuntu-latest
        outputs:
            release_version: ${{ steps.build.outputs.RELEASE_VERSION }}

        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Install dependencies
              run: npm install

            - name: Build from typescript files
              id: build
              run: npm run build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              id: deployment
              with:
                  path: ./dist
                  retention-days: 90

            - name: Get version from package.json
              run: |
                  release_version=$(npm v ./ version)
                  echo "RELEASE_VERSION=$release_version" >> $GITHUB_OUTPUT

    cleanup:
        runs-on: ubuntu-latest
        permissions: write-all

        steps:
            - name: Delete inactive deployments
              uses: strumwolf/delete-deployment-environment@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  environment: github-pages
                  onlyRemoveDeployments: true

    deploy:
        # Add a dependency to the build job
        needs:
            - build
            - cleanup
        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source
            contents: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Print all environment variables
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ needs.build.outputs.RELEASE_VERSION }}
              run: printenv

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                  token: ${{ github.token }}

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ needs.build.outputs.RELEASE_VERSION }}
              run: |
                  gh release create $tag \
                      --repo="$GITHUB_REPOSITORY" \
                      --title=$tag\
                      --generate-notes
