name: Release

# This workflow will run on main branch to build, test and deploy frontend application.
# SCM release tag will be created on repository as well.
on:
    push:
        branches:
            - main
            - develop

jobs:
    # this will build the artifacts needed for deploy using the npm run build command
    build:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Install dependencies
              run: npm install

            - name: Build from typescript files
              id: build
              run: npm run build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              id: deployment
              with:
                  path: ./dist
                  retention-days: 90

    deploy:
        # Add a dependency to the build job
        needs: build
        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source
            contents: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                  token: ${{ github.token }}

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ github.ref_name }}
              run: |
                  gh release create "$tag" \
                      --repo="$GITHUB_REPOSITORY" \
                      --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
                      --generate-notes
